### PR TITLE
Ensure types are bundled and correctly linked

### LINKED ISSUE #169: Type definitions are broken in 4.0.0-beta.1
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Type definitions are broken for both CJS and ESM.

### Reproduction

Create the following files:

```jsonc
// package.json
{
  "dependencies": {
    "jwt-decode": "4.0.0-beta.1",
    "typescript": "5.1.6"
  }
}
```

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "checkJs": true,
    "moduleResolution": "node16",
    "strict": true
  }
}
```

```js
// index.cjs
const jwtDecode = require('jwt-decode');

jwtDecode.default('')
```

This yields the following type error:

```
$ tsc
node_modules/jwt-decode/build/typings/index.d.ts:1:57 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

1 import { JwtDecodeOptions, JwtHeader, JwtPayload } from "./global";
                                                          ~~~~~~~~~~

node_modules/jwt-decode/build/typings/index.d.ts:2:15 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

2 export * from './global';
                ~~~~~~~~~~

script.cjs:1:27 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("jwt-decode")' call instead.

1 const jwtDecode = require('jwt-decode');
                            ~~~~~~~~~~~~


Found 3 errors in 2 files.

Errors  Files
     2  node_modules/jwt-decode/build/typings/index.d.ts:1
     1  script.cjs:1
```

This shows 2 errors:

1. According to the type definitions `jwt-decode` is ESM only, although there is a CJS entrypoint. To solve this, the exports in `package.json` should look something like this:
   ```jsonc
   {
       "exports": {
            ".": {
                "require": {
                    "types": "./build/typings/index.d.cts",
                    "default": "./build/cjs/jwt-decode.js"
                },
                "import": {
                    "types": "./build/typings/index.d.ts",
                    "default": "./build/esm/jwt-decode.js"
                }
            }
        }
    }
   ```
2. All imports should have the appropriate extension (`.js` in this case)
3. Even if the above 2 are fixed, the type definitions of the CJS module should look like this:
   ```ts
   declare function jwtDecode(/* … */) // …

    declare namespace jwtDecode {
     class InvalidTokenError extends Error {
       // …
     }
   }

   export = jwtDecode
   ```

### Additional context

The current build setup is relatively complex. Dual publishing is pretty complex. I’m not sure how to fix it in this setup. An alternative solution is to use a named export instead of a default export.

### jwt-decode version

4.0.0-beta.1

### Which browsers have you tested in?

Other

### PR DESCRIPTION
**Pull request by jonkoops**
Ensures that emitted types are bundled into a single file, and that both ESM and CommonJS have their own type definition files linked. This is done by adding a new script to generate the types using [`tsup`](https://github.com/egoist/tsup#tsup), which can bundle the types, unlike the TypeScript (see https://github.com/microsoft/TypeScript/issues/4433). 

Closes #169

### CODE REVIEW

File: lib/index.standalone.ts
Comment (jonkoops) [inline lib/index.standalone.ts:1]: I've renamed this file to `index.umd.ts` to better reflect it's purpose in the build.

**Comment by jonkoops** [comment]
@remcohaszing I took your suggestion from https://github.com/auth0/jwt-decode/issues/169#issuecomment-1657124641, and used the [Are the types wrong? CLI](https://github.com/arethetypeswrong/arethetypeswrong.github.io/tree/main/packages/cli) to verify the package:

A screenshot showing all checks passing

I'll see if I can introduce this as part of the build process in a subsequent PR, for now I wanted to keep this one lean and to the point. In the meantime, can I ask you to take a look at the changes here and let me know if this also matches your expectations?

File: package.json [hunk 1]
```diff
@@ -41,20 +56,13 @@
...
   "engines": {
     "node": ">=16"
-  },
-  "type": "module",
-  "exports": {
-    ".": {
-      "require": "./build/cjs/jwt-decode.js",
-      "import": "./build/esm/jwt-decode.js",
-      "types": "./build/typings/index.d.ts"
-    }
```
Comment (jonkoops) [inline package.json:58]: I've moved this up next to the `main` and `module` definitions, so that all the paths that export stuff are in the same place.

**Comment by remcohaszing** [comment]
This helps, but the CJS types are still wrong (ATTW is nice, but not yet perfect). They should not define `export default jwtDecode`, but:

```ts
declare function jwtDecode(/* … */) // …


declare namespace jwtDecode {
  class InvalidTokenError extends Error {
    // …
  }
}

export = jwtDecode
```

The simplest solution is to simply not use default exports, but named exports.

---

Also I believe `tsup` can just replace rollup here.

**Comment by jonkoops** [comment]
> This helps, but the CJS types are still wrong

I thought so at first as well, but it seems that if I set the `module` option to `CommonJS` the same output is produced. Even if I use `tsc` manually with a config that only compiles CommonJS I get the same result:

```json
{
  "files": [
    "./lib/index.ts"
  ],
  "compilerOptions": {
    "target": "ES5",
    "module": "CommonJS",
    "strict": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "declarationDir": "./typings",
  }
}
```

It seems like this is just how the TypeScript compiler wants to emit types for the CommonJS? Perhaps I am missing something, can you manage to get the output you expect with `tsc`?

> The simplest solution is to simply not use default exports, but named exports.

Totally agree, but that would be a breaking change. And @frederikprijck has made it clear that is [not an option for him](https://github.com/auth0/jwt-decode/pull/130#issuecomment-1651408765). 

> Also I believe `tsup` can just replace rollup here.

It could, but we can't do this because:

1. It does not support bundling UMD.
2. It cannot have mixed default and named exports for CommonJS, and neither can Rollup (which is why we [have this hack](https://github.com/auth0/jwt-decode/blob/fa904b3adc167c2d75af381b807649ed74a2766e/lib/index.cjs.js#L3-L6)).

My personal opinion aligns with you, which would be:

1. Do a major version bump for breaking changes.
2. Use named exports only, this avoids the aforementioned mixed exports issue.
3. Drop the UMD bundle (and possibly also CommonJS since we're doing a breaking change anyways)
4. Simplify tooling by dropping Rollup in favor of tsup.

But again, that would be a breaking change, which I don't believe is an option.

**Comment by frederikprijck** [comment]
Hey, i want to mention that introducing a breaking change for this is perfectly fine, but i would avoid it if not necessary. But it looks like it will be neccesary and i have no objections, sorry if it may have sounded like that before.

What i do not want is drop commonjs, for reasons mentioned before.

**Comment by cristobal** [comment]
Hmm @frederikprijck why is `main` set to `build/cjs/jwt-decode.js`, i think this could be a bit problematic when the type is module set in **package.json**.

Why not use the `exports` field instead?

**Comment by frederikprijck** [comment]
@cristobal can you elaborate on what's going wrong, probably outside of this PR

Not all tooling relies on exports, so we might need to support both.

**Comment by jonkoops** [comment]
> But it looks like it will be necessary and i have no objections, sorry if it may have sounded like that before.

@frederikprijck did not mean to imply you were holding this up or anything, just that it was a concern for backwards compatibility. Sorry if it came across as such. Some maintainers can be a bit more strict about backwards compatibility :stuck_out_tongue: 

> What i do not want is drop commonjs, for reasons mentioned before.

Yeah that should not be an issue, still complicates things slightly, but not as much if we decide to drop the default export. What is your take on the UMD module though? I'd personally prefer to get rid of it, but I understand if you feel differently.

> Regarding tsup, all our JavaScript SDKs (we have alot) are using rollup, so for several reasons i believe we should stick to it, unless there is a clear reason we can not.

There is a couple of reasons I can think of, but the main one would be that it already does everything we need (except for UMD), and that pretty much makes Rollup obsolete. It also follows all the best practices and could replace the config we have with a single line script entry in the package.

If you like, I can create a draft PR to show you what this could look like under ideal circumstances. Just to get an idea.

> So let's go with dropping default exports, but keep commonjs and rollup around.

Got it, I'll make a separate PR for that so we can land this quickly and without to many files to review.

**Comment by jonkoops** [comment]
> Why not use the `exports` field instead?

We already do, and this has not changed in this PR. I've just moved the code around a little. And as @frederikprijck mentioned, there is tooling out there that does not yet understand the `exports` field, so we keep `main` and `module` around for backwards compatibility.

**Comment by frederikprijck** [comment]
@jonkoops ,

I opened a PR (#175 ) to avoid default exports.

> What is your take on the UMD module though? I'd personally prefer to get rid of it, but I understand if you feel differently.

How would we support people currently relying on the UMD bundle, mostly by including the script tag in their HTML file?

**Comment by cristobal** [comment]
> This helps, but the CJS types are still wrong (ATTW is nice, but not yet perfect). They should not define `export default jwtDecode`, but:
> 
> ```ts
> declare function jwtDecode(/* … */) // …
> 
> 
> declare namespace jwtDecode {
>   class InvalidTokenError extends Error {
>     // …
>   }
> }
> 
> export = jwtDecode
> ```
> 
> The simplest solution is to simply not use default exports, but named exports.
> 
> Also I believe `tsup` can just replace rollup here.

This is what also rollup recommends, which is used for bundling here
https://rollupjs.org/configuration-options/#output-exports

**Comment by cristobal** [comment]
> @jonkoops ,
> 
> I opened a PR (#175 ) to avoid default exports.
> 
> > What is your take on the UMD module though? I'd personally prefer to get rid of it, but I understand if you feel differently.
> 
> How would we support people currently relying on the UMD bundle, mostly by including the script tag in their HTML file?

I'm not sure why you need to have an UMD bundle here, you can add it in the README that people relying on UMD can rather bundle it themselves or stick with the old version.

**Comment by jonkoops** [comment]
> How would we support people currently relying on the UMD bundle, mostly by including the script tag in their HTML file?

Well, by supporting ESM we can support them. They can import it as they would other modules:

```html
<script type="module">
  import { jwtDecode } from "/path-to-esm/jwt-decode.js";
  
  const token = "eyJ0eXAiO.../// jwt token";
  const decoded = jwtDecode(token);
</script>
```

Or alternatively, if an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) is used, this would look the same as ESM and Node.js:


```html
<script type="module">
  import { jwtDecode } from "jwt-decode";
</script>
```

**Comment by cristobal** [comment]
> > How would we support people currently relying on the UMD bundle, mostly by including the script tag in their HTML file?
> 
> Well, by supporting ESM we can support them. They can import it as they would other modules:
> 
> ```
> <script type="module">
>   import { jwtDecode } from "/path-to-esm/jwt-decode.js";
>   
>   const token = "eyJ0eXAiO.../// jwt token";
>   const decoded = jwtDecode(token);
> </script>
> ```
> 
> Or alternatively, if an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) is used, this would look the same as ESM and Node.js:
> 
> ```
> <script type="module">
>   import { jwtDecode } from "jwt-decode";
> </script>
> ```

Again as you say by supporting esm we can support them, however there is no need for an UMD js file then?

This is more of an Documentation issue rather than anything else, or am i missing something?

**Comment by jonkoops** [comment]
@cristobal I recommend you read my comments in this thread, I am not advocating for UMD.

**Comment by cristobal** [comment]
> @cristobal I recommend you read my comments in this thread, I am not advocating for UMD.

@jonkoops my questing was directed to @frederikprijck here.

**Comment by jonkoops** [comment]
Ok, got confused there since you are quoting my post.

**Comment by frederikprijck** [comment]
I have a feeling you both have a strong reason to drop it, while i believe don't see the issue.

If so, can you please open an issue so we can have a central place that elaborates on the issues with keeping it.

Please refrain from any personal opinion about wether or not we should support it, but elaborate on the reasons we should drop it beyond personal preference.

My opinion is to keep it, even if there are alternative paths for those users to migrate. I want to avoid unneccesarily breaking users beyond things that are needed.

**Comment by remcohaszing** [comment]
@jonkoops 

> It seems like this is just how the TypeScript compiler wants to emit types for the CommonJS?

Yes. This is correct. This results in the following build output:

```js
exports.default = jwtDecode
```

> Perhaps I am missing something, can you manage to get the output you expect with `tsc`?

Yes. TypeScript isn’t intended for dual publishing. It also can’t, because CJS and ESM are incompatible, especially default exports. To get proper output, you need both CJS and ESM source files.

Named exports make it simpler though. Because now this:

```ts
export function jwtDecode() {}
```

can be compiled to:

```js
function jwtDecode() {}

exports.jwtDecode = jwtDecode
```

---

The problem with Rollup and other third party TypeScript build tools is, they understand JavaScript, but not TypeScript. Aside from `tsc`, `tsup` is the only tool that does this somewhat correctly (though it can’t transform default exports as desirable).

I doubt if people actually still use UMD. However, rollup could still be used to produce only the UMD bundle.

**Comment by jonkoops** [comment]
I agree with @frederikprijck, let's move the UMD discussion to a separate issue. I think it's just cluttering up the discussion here. I've created #180 to continue this discussion.

**Comment by jonkoops** [comment]
> Yes. TypeScript isn’t intended for dual publishing. It also can’t, because CJS and ESM are incompatible, especially default exports. To get proper output, you need both CJS and ESM source files.

Sigh, dual packaging is like the gift bag of needles that never stops giving. Any idea how we can accomplish this without creating new source code?

**Comment by remcohaszing** [comment]
This looks fine.

The following CJS export style:

```js
exports.InvalidTokenError = InvalidTokenError;
exports.jwtDecode = jwtDecode;
```

requires the following type definitions:

```ts
export {
  InvalidTokenError,
  jwtDecode
}
```

However, the following CJS exports style:

```js
module.exports = something;
```

Requires the following type definitions:

```ts
export = something;
```

This is why named exports solve many ESM/CJS compatibility issues for dual publishing.

**Comment by remcohaszing** [comment]
There is some documentation in https://www.typescriptlang.org/docs/handbook/modules.html and https://www.typescriptlang.org/docs/handbook/esm-node.html, but IMO the explanation isn’t great. [This draft document](https://gist.github.com/andrewbranch/79f872a8b9f0507c9c5f2641cfb3efa6) explains a lot more in depth, but it’s a lot to read and not finished.

Really the best thing you can do is fiddle with a simple project:

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true,
    "module": "node16"
  }
}
```

```ts
// foo.cts
export interface Options {}

export function foo(options: Options) {}
```

```ts
// bar.cts
declare namespace bar {
  interface Options {}
}

function bar(options: bar.Options) {}

export = bar
```

and then fiddle yourself. See what the output is when running `tsc`

**Comment by jonkoops** [comment]
@remcohaszing Yeah, I am getting the same. Let's consider this resolved then :+1:

**Comment by jonkoops** [comment]
Just did a quick rebase so the changes from #175 are included, so I think this is good to go. @remcohaszing @frederikprijck would you take another look and let me know if things look good?

File: package.json [hunk 2]
```diff
@@ -17,8 +30,10 @@
   "homepage": "https://github.com/auth0/jwt-decode#readme",
   "scripts": {
     "dev": "rollup --sourcemap --config --configPlugin typescript",
-    "build": "rimraf build && rollup --sourcemap --config --configPlugin typescript --environment NODE_ENV:production",
-    "postbuild": "echo '{\"type\": \"commonjs\"}'> build/cjs/package.json",
```
Comment (frederikprijck) [inline package.json:21]: Do we no longer need this?

Comment (jonkoops) [reply package.json:21]: Yeah, you are right. Now that we're using the `.cjs` extension this should work without this. I'll remove it.

**Review by frederikprijck — APPROVED** [review]
Thanks for the work here, this looks great.

**Comment by remcohaszing** [comment]
Yes, this works great! Thanks!

**Comment by jonkoops** [comment]
Thanks for getting this landed all!
